questions = [
    "What's your most unforgettable Vegas story?",
    "Ever had a date go unexpectedly wild? What happened?",
    "What's the craziest thing you've done for love?",
    "What was your most memorable 'lost in translation' moment while traveling?",
    "Have you ever found something surprising in a hotel room? What was it?",
    "What's the most bizarre thing you've witnessed at a party?",
    "Ever had a celebrity encounter that turned awkward? Spill the beans!",
    "What's the funniest thing you've seen happen in a public place?",
    "Share your most embarrassing gym story.",
    "Ever sent a text to the wrong person that you immediately regretted? What was it about?",
    "What's the wildest thing you've done on a dare?",
    "Have you ever crashed a wedding or a party? What was the outcome?",
    "What's the most unusual pet you've ever encountered?",
    "Ever tried to cook something fancy and it turned into a disaster? Describe.",
    "What's your funniest 'thought the microphone was off' story?",
    "Have you ever been mistaken for someone famous? What happened?",
    "What's the most awkward situation you've been in at work?",
    "Ever gone on a trip that turned adventurous for unexpected reasons?",
    "What's your best story of miscommunication leading to a happy mistake?",
    "Ever had a bizarre encounter with a neighbor? What was it about?",
    "What's the most creative way you've seen someone solve a problem?",
    "Ever been part of a flash mob or a surprise public performance? Share your experience.",
    "What's the strangest gift you've ever received?",
    "Ever had a moment where you thought, 'I'm in a sitcom'? What was happening?",
    "What's the most outrageous outfit you've worn to a theme party?",
    "Have you ever participated in a contest that had a funny outcome?",
    "What's the most unexpected thing you've learned from a stranger?",
    "Ever experienced a 'small world' moment that left you baffled? Describe it.",
    "What's the funniest misunderstanding you've had due to autocorrect?",
    "Ever stumbled upon a secret spot in your city? What made it special?",
    'What is your most unforgettable travel experience?',
    'Can you share an inspiring personal success story?',
    'What\'s the most intriguing ghost story or urban legend you\'ve ever heard?',
    'Describe an encounter with a wild animal that left you speechless.',
    'What\'s your favorite childhood memory that still brings joy to your life?',
    'Tell us about a time when you had to make a difficult decision and the outcome.',
    'Can you share an emotional, heartwarming or funny story from your family history?',
    'Describe a magical moment in nature that took your breath away.',
    'What\'s the most fascinating encounter you\'ve ever had with a stranger?',
    'Share a hilarious or touching experience you\'ve had with friends.',
    'Can you tell us about an adventure that changed your perspective on life?',
    'Describe the time when you felt truly alive and free.',
    'What is the most incredible act of kindness you have ever witnessed?',
    'Tell us about a pet that touched your heart.',
    'Share an experience where you overcame a fear or phobia.',
    'Can you describe a moment when you had to make amends for a past mistake?',
    'Describe the most beautiful sunset or sunrise you\'ve ever seen.',
    'Tell us about an experience where you learned an important lesson from failure.',
    'Share a story about a time when you helped someone in need.',
    'Can you describe an encounter with a famous person that left a lasting impression?',
    'Describe a moment when you felt truly connected to another person.',
    'Tell us about a time when you witnessed a natural disaster and its aftermath.',
    'Share a story about a friendship or romantic relationship that changed your life.',
    'Can you describe an experience where you had an unexplainable feeling of déjà vu?',
    'Describe the most beautiful place you\'ve ever visited, and why it stands out to you.',
    'Tell us about a time when you were lost and how you found your way back.',
    'Share a story about a life-changing event that occurred during a significant turning point in your life.',
    'Can you describe an experience where you felt a deep sense of accomplishment?',
    'Tell us about a moment when you discovered a hidden talent or ability within yourself.',
    'Share a story about a time when you were surprised by a kind gesture from someone unexpected.',
    'Describe the most beautiful piece of art, music, or literature that touched your soul.',
    'Can you tell us about a time when you overcame adversity with resilience?',
    'Tell us about a moment when you felt truly inspired and created something beautiful.',
    'Share a story about a time when you traveled to a new place and were amazed by the culture.',
    'Describe an encounter with an extraordinary person that left a profound impact on your life.',
    'Can you tell us about a moment of serendipity or chance that changed the course of your life?',
    'Share a story about a time when you faced a challenge and learned from it.',
    'Describe the most memorable birthday or celebration in your life.',
    'Tell us about an experience where you witnessed an act of bravery or courage.',
    'Share a story about a time when you had to rely on your intuition and trust yourself.',
    'Describe a moment when you felt truly in love or deeply connected to someone.',
    'Describe an encounter with a mythical creature or otherworldly being that left you in awe.'
]

story_types = [
    'Travel experiences',
    'Personal success stories',
    'Ghost stories and urban legends',
    'Encounters with wild animals',
    'Favorite childhood memories',
    'Difficult decisions and their outcomes',
    'Family history stories (emotional, heartwarming, funny)',
    'Magical moments in nature',
    'Encounters with fascinating strangers',
    'Hilarious or touching experiences with friends',
    'Life-changing adventures',
    'Moments of feeling alive and free',
    'Incredible acts of kindness',
    'Stories about beloved pets',
    'Experiences overcoming fears or phobias',
    'Moments of amends for past mistakes',
    'Sunsets or sunrises descriptions',
    'Lessons learned from failures',
    'Helping someone in need stories',
    'Encounters with famous people',
    'Deep connections with others',
    'Natural disaster experiences and aftermaths',
    'Stories about friendships or romantic relationships',
    'Déjà vu experiences',
    'Descriptions of beautiful places',
    'Getting lost and finding the way back',
    'Life-changing events during turning points',
    'Describing moments of deep accomplishment',
    'Discovering hidden talents or abilities',
    'Unexpected kind gestures',
    'Beautiful pieces of art, music, or literature',
    'Stories of overcoming adversity',
    'Inspiring stories of creation',
    'New cultural experiences while traveling',
    'Encounters with extraordinary people',
    'Moments of serendipity or chance'
]

adjectives = [
    'Unforgettable', 'Inspiring', 'Scary', 'Raunchy', 'Thrilling', 'Mystical', 'Adventurous', 'Emotional', 'Heartwarming', 'Funny',
    'Dramatic', 'Mind-blowing', 'Awe-inspiring', 'Amusing', 'Romantic', 'Intense', 'Exciting', 'Surreal', 'Provocative', 'Suspenseful',
    'Memorable', 'Hilarious', 'Touching', 'Breathtaking', 'Fascinating', 'Joyful', 'Incredible', 'Moving', 'Magical', 'Thought-provoking',
    'Challenging', 'Sensational', 'Entertaining', 'Enlightening', 'Uplifting', 'Insightful', 'Eye-opening', 'Mesmerizing', 'Bizarre',
    'Whimsical', 'Quirky', 'Mysterious', 'Fascinating', 'Narrative', 'Engaging', 'Captivating', 'Memorable', 'Suspenseful'
]