questions = [
    "What's your most unforgettable Vegas story?",
    "Ever had a date go unexpectedly wild? What happened?",
    "What's the craziest thing you've done for love?",
    "What was your most memorable 'lost in translation' moment while traveling?",
    "Have you ever found something surprising in a hotel room? What was it?",
    "What's the most bizarre thing you've witnessed at a party?",
    "Ever had a celebrity encounter that turned awkward? Spill the beans!",
    "What's the funniest thing you've seen happen in a public place?",
    "Share your most embarrassing gym story.",
    "Ever sent a text to the wrong person that you immediately regretted? What was it about?",
    "What's the wildest thing you've done on a dare?",
    "Have you ever crashed a wedding or a party? What was the outcome?",
    "What's the most unusual pet you've ever encountered?",
    "Ever tried to cook something fancy and it turned into a disaster? Describe.",
    "What's your funniest 'thought the microphone was off' story?",
    "Have you ever been mistaken for someone famous? What happened?",
    "What's the most awkward situation you've been in at work?",
    "Ever gone on a trip that turned adventurous for unexpected reasons?",
    "What's your best story of miscommunication leading to a happy mistake?",
    "Ever had a bizarre encounter with a neighbor? What was it about?",
    "What's the most creative way you've seen someone solve a problem?",
    "Ever been part of a flash mob or a surprise public performance? Share your experience.",
    "What's the strangest gift you've ever received?",
    "Ever had a moment where you thought, 'I'm in a sitcom'? What was happening?",
    "What's the most outrageous outfit you've worn to a theme party?",
    "Have you ever participated in a contest that had a funny outcome?",
    "What's the most unexpected thing you've learned from a stranger?",
    "Ever experienced a 'small world' moment that left you baffled? Describe it.",
    "What's the funniest misunderstanding you've had due to autocorrect?",
    "Ever stumbled upon a secret spot in your city? What made it special?"
]